# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc



class CommonServiceStub(object):
  """公共服务
  弃用
  // 返回省份列表
  rpc listProvince (RequestListProvince) returns (AddressListMsg){}
  // 返回城市列表
  rpc listCity (RequestListCity) returns (AddressListMsg){}
  // 返回区/县列表
  rpc listDistrict (RequestListDistrict) returns (AddressListMsg){}
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """


class CommonServiceServicer(object):
  """公共服务
  弃用
  // 返回省份列表
  rpc listProvince (RequestListProvince) returns (AddressListMsg){}
  // 返回城市列表
  rpc listCity (RequestListCity) returns (AddressListMsg){}
  // 返回区/县列表
  rpc listDistrict (RequestListDistrict) returns (AddressListMsg){}
  """


def add_CommonServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'customercenter.CommonService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
