# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CCCommonMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='CCCommonMessage.proto',
  package='customercenter',
  syntax='proto3',
  serialized_options=_b('\n1com.szwdcloud.customercenter.proto.customercenterB\024CCCommonMessageProtoP\001'),
  serialized_pb=_b('\n\x15\x43\x43\x43ommonMessage.proto\x12\x0e\x63ustomercenter\x1a\x19google/protobuf/any.proto\"\x9a\x01\n\x12\x43\x43\x42\x61tchDataPageMsg\x12\x0e\n\x06pageNo\x18\x01 \x01(\x05\x12\x10\n\x08pagesize\x18\x02 \x01(\x05\x12\r\n\x05pages\x18\x03 \x01(\x05\x12\x14\n\x0ctotalRecords\x18\x04 \x01(\x02\x12\"\n\x04rows\x18\x05 \x01(\x0b\x32\x14.google.protobuf.Any\x12\x0c\n\x04\x63ode\x18\x06 \x01(\t\x12\x0b\n\x03msg\x18\x07 \x01(\t\"=\n\x19\x43\x43\x44\x61taPageRequestParamMsg\x12\x0e\n\x06pageNo\x18\x01 \x01(\x05\x12\x10\n\x08pagesize\x18\x02 \x01(\x05\"I\n\x08ReplyMsg\x12\"\n\x04rows\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0b\n\x03msg\x18\x03 \x01(\tBK\n1com.szwdcloud.customercenter.proto.customercenterB\x14\x43\x43\x43ommonMessageProtoP\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])




_CCBATCHDATAPAGEMSG = _descriptor.Descriptor(
  name='CCBatchDataPageMsg',
  full_name='customercenter.CCBatchDataPageMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pageNo', full_name='customercenter.CCBatchDataPageMsg.pageNo', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pagesize', full_name='customercenter.CCBatchDataPageMsg.pagesize', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pages', full_name='customercenter.CCBatchDataPageMsg.pages', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='totalRecords', full_name='customercenter.CCBatchDataPageMsg.totalRecords', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rows', full_name='customercenter.CCBatchDataPageMsg.rows', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code', full_name='customercenter.CCBatchDataPageMsg.code', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='customercenter.CCBatchDataPageMsg.msg', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=223,
)


_CCDATAPAGEREQUESTPARAMMSG = _descriptor.Descriptor(
  name='CCDataPageRequestParamMsg',
  full_name='customercenter.CCDataPageRequestParamMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pageNo', full_name='customercenter.CCDataPageRequestParamMsg.pageNo', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pagesize', full_name='customercenter.CCDataPageRequestParamMsg.pagesize', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=286,
)


_REPLYMSG = _descriptor.Descriptor(
  name='ReplyMsg',
  full_name='customercenter.ReplyMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rows', full_name='customercenter.ReplyMsg.rows', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code', full_name='customercenter.ReplyMsg.code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='customercenter.ReplyMsg.msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=288,
  serialized_end=361,
)

_CCBATCHDATAPAGEMSG.fields_by_name['rows'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_REPLYMSG.fields_by_name['rows'].message_type = google_dot_protobuf_dot_any__pb2._ANY
DESCRIPTOR.message_types_by_name['CCBatchDataPageMsg'] = _CCBATCHDATAPAGEMSG
DESCRIPTOR.message_types_by_name['CCDataPageRequestParamMsg'] = _CCDATAPAGEREQUESTPARAMMSG
DESCRIPTOR.message_types_by_name['ReplyMsg'] = _REPLYMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CCBatchDataPageMsg = _reflection.GeneratedProtocolMessageType('CCBatchDataPageMsg', (_message.Message,), dict(
  DESCRIPTOR = _CCBATCHDATAPAGEMSG,
  __module__ = 'CCCommonMessage_pb2'
  # @@protoc_insertion_point(class_scope:customercenter.CCBatchDataPageMsg)
  ))
_sym_db.RegisterMessage(CCBatchDataPageMsg)

CCDataPageRequestParamMsg = _reflection.GeneratedProtocolMessageType('CCDataPageRequestParamMsg', (_message.Message,), dict(
  DESCRIPTOR = _CCDATAPAGEREQUESTPARAMMSG,
  __module__ = 'CCCommonMessage_pb2'
  # @@protoc_insertion_point(class_scope:customercenter.CCDataPageRequestParamMsg)
  ))
_sym_db.RegisterMessage(CCDataPageRequestParamMsg)

ReplyMsg = _reflection.GeneratedProtocolMessageType('ReplyMsg', (_message.Message,), dict(
  DESCRIPTOR = _REPLYMSG,
  __module__ = 'CCCommonMessage_pb2'
  # @@protoc_insertion_point(class_scope:customercenter.ReplyMsg)
  ))
_sym_db.RegisterMessage(ReplyMsg)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
