# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import RespondTSBService_pb2 as RespondTSBService__pb2


class RespondTSBServiceStub(object):
  """响应学校后台请求
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.login = channel.unary_unary(
        '/operating.platform.RespondTSBService/login',
        request_serializer=RespondTSBService__pb2.RequestLoginTOP.SerializeToString,
        response_deserializer=RespondTSBService__pb2.RespondLoginTSB.FromString,
        )
    self.listSchoolGradeBySchoolId = channel.unary_unary(
        '/operating.platform.RespondTSBService/listSchoolGradeBySchoolId',
        request_serializer=RespondTSBService__pb2.RequestSchoolGradeTOP.SerializeToString,
        response_deserializer=RespondTSBService__pb2.RespondSchoolGradeTSB.FromString,
        )
    self.listSchoolingLengthBySchoolId = channel.unary_unary(
        '/operating.platform.RespondTSBService/listSchoolingLengthBySchoolId',
        request_serializer=RespondTSBService__pb2.RequestSchoolingLengthTOP.SerializeToString,
        response_deserializer=RespondTSBService__pb2.RespondSchoolingLengthTSB.FromString,
        )
    self.listSchoolingLengthSchoolGradeBySchoolId = channel.unary_unary(
        '/operating.platform.RespondTSBService/listSchoolingLengthSchoolGradeBySchoolId',
        request_serializer=RespondTSBService__pb2.RequestSchoolingLengthSchoolGradeTOP.SerializeToString,
        response_deserializer=RespondTSBService__pb2.RespondSchoolingLengthSchoolGradeTSB.FromString,
        )
    self.listSubjectBySchoolId = channel.unary_unary(
        '/operating.platform.RespondTSBService/listSubjectBySchoolId',
        request_serializer=RespondTSBService__pb2.RequestSubjectTOP.SerializeToString,
        response_deserializer=RespondTSBService__pb2.RespondSubjectTSB.FromString,
        )
    self.listSubjectSchoolGradeBySubjectId = channel.unary_unary(
        '/operating.platform.RespondTSBService/listSubjectSchoolGradeBySubjectId',
        request_serializer=RespondTSBService__pb2.RequestSubjectSchoolGradeTOP.SerializeToString,
        response_deserializer=RespondTSBService__pb2.RespondSubjectSchoolGradeTSB.FromString,
        )
    self.listSchoolGradeSubjectById = channel.unary_unary(
        '/operating.platform.RespondTSBService/listSchoolGradeSubjectById',
        request_serializer=RespondTSBService__pb2.RequestSchoolGradeSubjectTOP.SerializeToString,
        response_deserializer=RespondTSBService__pb2.RespondSchoolGradeSubjectTSB.FromString,
        )
    self.listPress = channel.unary_unary(
        '/operating.platform.RespondTSBService/listPress',
        request_serializer=RespondTSBService__pb2.RequestPressTOP.SerializeToString,
        response_deserializer=RespondTSBService__pb2.RespondPressTSB.FromString,
        )
    self.listEditionBySchoolGradeSubjectPressId = channel.unary_unary(
        '/operating.platform.RespondTSBService/listEditionBySchoolGradeSubjectPressId',
        request_serializer=RespondTSBService__pb2.RequestEditionTOP.SerializeToString,
        response_deserializer=RespondTSBService__pb2.RespondEditionTSB.FromString,
        )
    self.listCustomerRole = channel.unary_unary(
        '/operating.platform.RespondTSBService/listCustomerRole',
        request_serializer=RespondTSBService__pb2.RequestCustomerRoleTOP.SerializeToString,
        response_deserializer=RespondTSBService__pb2.RespondCustomerRoleTSB.FromString,
        )


class RespondTSBServiceServicer(object):
  """响应学校后台请求
  """

  def login(self, request, context):
    """登录
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def listSchoolGradeBySchoolId(self, request, context):
    """根据学校返回年级列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def listSchoolingLengthBySchoolId(self, request, context):
    """根据学校返回学制列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def listSchoolingLengthSchoolGradeBySchoolId(self, request, context):
    """根据学制返回学制年级列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def listSubjectBySchoolId(self, request, context):
    """根据学校id返回科目列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def listSubjectSchoolGradeBySubjectId(self, request, context):
    """根据科目id获取科目年级列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def listSchoolGradeSubjectById(self, request, context):
    """根据年级id返回年级科目列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def listPress(self, request, context):
    """返回出版社列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def listEditionBySchoolGradeSubjectPressId(self, request, context):
    """根据年级科目出版社返回教材列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def listCustomerRole(self, request, context):
    """返回客户角色列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RespondTSBServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'login': grpc.unary_unary_rpc_method_handler(
          servicer.login,
          request_deserializer=RespondTSBService__pb2.RequestLoginTOP.FromString,
          response_serializer=RespondTSBService__pb2.RespondLoginTSB.SerializeToString,
      ),
      'listSchoolGradeBySchoolId': grpc.unary_unary_rpc_method_handler(
          servicer.listSchoolGradeBySchoolId,
          request_deserializer=RespondTSBService__pb2.RequestSchoolGradeTOP.FromString,
          response_serializer=RespondTSBService__pb2.RespondSchoolGradeTSB.SerializeToString,
      ),
      'listSchoolingLengthBySchoolId': grpc.unary_unary_rpc_method_handler(
          servicer.listSchoolingLengthBySchoolId,
          request_deserializer=RespondTSBService__pb2.RequestSchoolingLengthTOP.FromString,
          response_serializer=RespondTSBService__pb2.RespondSchoolingLengthTSB.SerializeToString,
      ),
      'listSchoolingLengthSchoolGradeBySchoolId': grpc.unary_unary_rpc_method_handler(
          servicer.listSchoolingLengthSchoolGradeBySchoolId,
          request_deserializer=RespondTSBService__pb2.RequestSchoolingLengthSchoolGradeTOP.FromString,
          response_serializer=RespondTSBService__pb2.RespondSchoolingLengthSchoolGradeTSB.SerializeToString,
      ),
      'listSubjectBySchoolId': grpc.unary_unary_rpc_method_handler(
          servicer.listSubjectBySchoolId,
          request_deserializer=RespondTSBService__pb2.RequestSubjectTOP.FromString,
          response_serializer=RespondTSBService__pb2.RespondSubjectTSB.SerializeToString,
      ),
      'listSubjectSchoolGradeBySubjectId': grpc.unary_unary_rpc_method_handler(
          servicer.listSubjectSchoolGradeBySubjectId,
          request_deserializer=RespondTSBService__pb2.RequestSubjectSchoolGradeTOP.FromString,
          response_serializer=RespondTSBService__pb2.RespondSubjectSchoolGradeTSB.SerializeToString,
      ),
      'listSchoolGradeSubjectById': grpc.unary_unary_rpc_method_handler(
          servicer.listSchoolGradeSubjectById,
          request_deserializer=RespondTSBService__pb2.RequestSchoolGradeSubjectTOP.FromString,
          response_serializer=RespondTSBService__pb2.RespondSchoolGradeSubjectTSB.SerializeToString,
      ),
      'listPress': grpc.unary_unary_rpc_method_handler(
          servicer.listPress,
          request_deserializer=RespondTSBService__pb2.RequestPressTOP.FromString,
          response_serializer=RespondTSBService__pb2.RespondPressTSB.SerializeToString,
      ),
      'listEditionBySchoolGradeSubjectPressId': grpc.unary_unary_rpc_method_handler(
          servicer.listEditionBySchoolGradeSubjectPressId,
          request_deserializer=RespondTSBService__pb2.RequestEditionTOP.FromString,
          response_serializer=RespondTSBService__pb2.RespondEditionTSB.SerializeToString,
      ),
      'listCustomerRole': grpc.unary_unary_rpc_method_handler(
          servicer.listCustomerRole,
          request_deserializer=RespondTSBService__pb2.RequestCustomerRoleTOP.FromString,
          response_serializer=RespondTSBService__pb2.RespondCustomerRoleTSB.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'operating.platform.RespondTSBService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
