# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SBCommonRespond.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='SBCommonRespond.proto',
  package='schoolbackground',
  syntax='proto3',
  serialized_options=_b('\n\030com.wd.proto.base.commonB\013ResultProtoP\001'),
  serialized_pb=_b('\n\x15SBCommonRespond.proto\x12\x10schoolbackground\x1a\x19google/protobuf/any.proto\"#\n\x06Result\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t\"0\n\x0bResultDatas\x12!\n\x03\x61ny\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\"4\n\x0fResultDatasList\x12!\n\x03\x61ny\x18\x01 \x03(\x0b\x32\x14.google.protobuf.AnyB)\n\x18\x63om.wd.proto.base.commonB\x0bResultProtoP\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])




_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='schoolbackground.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='schoolbackground.Result.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='schoolbackground.Result.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=105,
)


_RESULTDATAS = _descriptor.Descriptor(
  name='ResultDatas',
  full_name='schoolbackground.ResultDatas',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='any', full_name='schoolbackground.ResultDatas.any', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=155,
)


_RESULTDATASLIST = _descriptor.Descriptor(
  name='ResultDatasList',
  full_name='schoolbackground.ResultDatasList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='any', full_name='schoolbackground.ResultDatasList.any', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=209,
)

_RESULTDATAS.fields_by_name['any'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_RESULTDATASLIST.fields_by_name['any'].message_type = google_dot_protobuf_dot_any__pb2._ANY
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
DESCRIPTOR.message_types_by_name['ResultDatas'] = _RESULTDATAS
DESCRIPTOR.message_types_by_name['ResultDatasList'] = _RESULTDATASLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
  DESCRIPTOR = _RESULT,
  __module__ = 'SBCommonRespond_pb2'
  # @@protoc_insertion_point(class_scope:schoolbackground.Result)
  ))
_sym_db.RegisterMessage(Result)

ResultDatas = _reflection.GeneratedProtocolMessageType('ResultDatas', (_message.Message,), dict(
  DESCRIPTOR = _RESULTDATAS,
  __module__ = 'SBCommonRespond_pb2'
  # @@protoc_insertion_point(class_scope:schoolbackground.ResultDatas)
  ))
_sym_db.RegisterMessage(ResultDatas)

ResultDatasList = _reflection.GeneratedProtocolMessageType('ResultDatasList', (_message.Message,), dict(
  DESCRIPTOR = _RESULTDATASLIST,
  __module__ = 'SBCommonRespond_pb2'
  # @@protoc_insertion_point(class_scope:schoolbackground.ResultDatasList)
  ))
_sym_db.RegisterMessage(ResultDatasList)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
