# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import RCCommon_pb2 as RCCommon__pb2
import RCReviewService_pb2 as RCReviewService__pb2


class RCReviewServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.submitResource = channel.unary_unary(
        '/resourcecenter.RCReviewService/submitResource',
        request_serializer=RCReviewService__pb2.Resource2ReviewReq.SerializeToString,
        response_deserializer=RCCommon__pb2.EmptyResp.FromString,
        )
    self.reviewResource = channel.unary_unary(
        '/resourcecenter.RCReviewService/reviewResource',
        request_serializer=RCReviewService__pb2.ReviewResourceReq.SerializeToString,
        response_deserializer=RCCommon__pb2.EmptyResp.FromString,
        )


class RCReviewServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def submitResource(self, request, context):
    """提交审核
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def reviewResource(self, request, context):
    """审核资源
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RCReviewServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'submitResource': grpc.unary_unary_rpc_method_handler(
          servicer.submitResource,
          request_deserializer=RCReviewService__pb2.Resource2ReviewReq.FromString,
          response_serializer=RCCommon__pb2.EmptyResp.SerializeToString,
      ),
      'reviewResource': grpc.unary_unary_rpc_method_handler(
          servicer.reviewResource,
          request_deserializer=RCReviewService__pb2.ReviewResourceReq.FromString,
          response_serializer=RCCommon__pb2.EmptyResp.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'resourcecenter.RCReviewService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
