# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import RCSchoolingLengthService_pb2 as RCSchoolingLengthService__pb2


class RCSchoolinglengthServiceStub(object):
  """学制
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.listSchoolingLength = channel.unary_unary(
        '/resourcecenter.RCSchoolinglengthService/listSchoolingLength',
        request_serializer=RCSchoolingLengthService__pb2.RequestSchoolingLength.SerializeToString,
        response_deserializer=RCSchoolingLengthService__pb2.ResponseSchoolingLengthList.FromString,
        )


class RCSchoolinglengthServiceServicer(object):
  """学制
  """

  def listSchoolingLength(self, request, context):
    """获取学制
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RCSchoolinglengthServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'listSchoolingLength': grpc.unary_unary_rpc_method_handler(
          servicer.listSchoolingLength,
          request_deserializer=RCSchoolingLengthService__pb2.RequestSchoolingLength.FromString,
          response_serializer=RCSchoolingLengthService__pb2.ResponseSchoolingLengthList.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'resourcecenter.RCSchoolinglengthService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
