# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RCSubjectService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RCCommon_pb2 as RCCommon__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='RCSubjectService.proto',
  package='resourcecenter',
  syntax='proto3',
  serialized_options=_b('\n\036com.szwdcloud.resource.subjectB\025RCSubjectServiceProtoP\001'),
  serialized_pb=_b('\n\x16RCSubjectService.proto\x12\x0eresourcecenter\x1a\x0eRCCommon.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\"*\n\x07Subject\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x13\n\x0bsubjectName\x18\x02 \x01(\t2\xa4\x01\n\x10RCSubjectService\x12\x41\n\x0blistSubject\x12\x16.google.protobuf.Empty\x1a\x18.resourcecenter.ListResp\"\x00\x12M\n\x12listSubjectByStage\x12\x1b.google.protobuf.Int32Value\x1a\x18.resourcecenter.ListResp\"\x00\x42\x39\n\x1e\x63om.szwdcloud.resource.subjectB\x15RCSubjectServiceProtoP\x01\x62\x06proto3')
  ,
  dependencies=[RCCommon__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,])




_SUBJECT = _descriptor.Descriptor(
  name='Subject',
  full_name='resourcecenter.Subject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='resourcecenter.Subject.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subjectName', full_name='resourcecenter.Subject.subjectName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=161,
)

DESCRIPTOR.message_types_by_name['Subject'] = _SUBJECT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Subject = _reflection.GeneratedProtocolMessageType('Subject', (_message.Message,), dict(
  DESCRIPTOR = _SUBJECT,
  __module__ = 'RCSubjectService_pb2'
  # @@protoc_insertion_point(class_scope:resourcecenter.Subject)
  ))
_sym_db.RegisterMessage(Subject)


DESCRIPTOR._options = None

_RCSUBJECTSERVICE = _descriptor.ServiceDescriptor(
  name='RCSubjectService',
  full_name='resourcecenter.RCSubjectService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=164,
  serialized_end=328,
  methods=[
  _descriptor.MethodDescriptor(
    name='listSubject',
    full_name='resourcecenter.RCSubjectService.listSubject',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=RCCommon__pb2._LISTRESP,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='listSubjectByStage',
    full_name='resourcecenter.RCSubjectService.listSubjectByStage',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_wrappers__pb2._INT32VALUE,
    output_type=RCCommon__pb2._LISTRESP,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RCSUBJECTSERVICE)

DESCRIPTOR.services_by_name['RCSubjectService'] = _RCSUBJECTSERVICE

# @@protoc_insertion_point(module_scope)
