# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import BMManagerService_pb2 as BMManagerService__pb2


class BMManagerServiceStub(object):
  """///////////////////////////////service//////////////////////////////////////
  分域权限
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.listRoleUserData = channel.unary_unary(
        '/basicmanagement.BMManagerService/listRoleUserData',
        request_serializer=BMManagerService__pb2.RequestRoleUserData.SerializeToString,
        response_deserializer=BMManagerService__pb2.ResponseRoleUserData.FromString,
        )
    self.listOperationManagerData = channel.unary_unary(
        '/basicmanagement.BMManagerService/listOperationManagerData',
        request_serializer=BMManagerService__pb2.RequestId.SerializeToString,
        response_deserializer=BMManagerService__pb2.ResponseSchoolListByOperationManagerId.FromString,
        )


class BMManagerServiceServicer(object):
  """///////////////////////////////service//////////////////////////////////////
  分域权限
  """

  def listRoleUserData(self, request, context):
    """运营经理,销售经理的关联查询(查询他的客户数,学校数,班级数,学生数)
    目前的需求是只查运营经理的,roleName传"运营"
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def listOperationManagerData(self, request, context):
    """查询某个运营经理的相关信息,他负责的学校,教师数,班级数,学生数
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BMManagerServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'listRoleUserData': grpc.unary_unary_rpc_method_handler(
          servicer.listRoleUserData,
          request_deserializer=BMManagerService__pb2.RequestRoleUserData.FromString,
          response_serializer=BMManagerService__pb2.ResponseRoleUserData.SerializeToString,
      ),
      'listOperationManagerData': grpc.unary_unary_rpc_method_handler(
          servicer.listOperationManagerData,
          request_deserializer=BMManagerService__pb2.RequestId.FromString,
          response_serializer=BMManagerService__pb2.ResponseSchoolListByOperationManagerId.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'basicmanagement.BMManagerService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
