# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BMManagerService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='BMManagerService.proto',
  package='basicmanagement',
  syntax='proto3',
  serialized_options=_b('\n3com.szwdcloud.basicmanagement.proto.basicmanagementB\025BMManagerServiceProtoP\001'),
  serialized_pb=_b('\n\x16\x42MManagerService.proto\x12\x0f\x62\x61sicmanagement\"\x17\n\tRequestId\x12\n\n\x02id\x18\x01 \x01(\t\"t\n&ResponseSchoolListByOperationManagerId\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12/\n\nschoolInfo\x18\x03 \x03(\x0b\x32\x1b.basicmanagement.SchoolInfo\"\xab\x01\n\nSchoolInfo\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x14\n\x0c\x63ustomerType\x18\x03 \x01(\x05\x12\x12\n\nteacherNum\x18\x04 \x01(\x05\x12\x10\n\x08\x63lassNum\x18\x05 \x01(\x05\x12\x12\n\nstudentNum\x18\x06 \x01(\x05\x12\x33\n\x0c\x43ustomerInfo\x18\x07 \x03(\x0b\x32\x1d.basicmanagement.CustomerInfo\"N\n\x0c\x43ustomerInfo\x12\x12\n\nsuperiorId\x18\x01 \x01(\x03\x12\x14\n\x0csuperiorName\x18\x02 \x01(\t\x12\x14\n\x0c\x63ustomerType\x18\x03 \x01(\x05\"\x9d\x01\n\x14ResponseRoleUserData\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\r\n\x05total\x18\x03 \x01(\x03\x12\r\n\x05pages\x18\x04 \x01(\x05\x12\x0e\n\x06pageNo\x18\x05 \x01(\x05\x12\x10\n\x08pageSize\x18\x06 \x01(\x05\x12*\n\x05\x64\x61tas\x18\x07 \x03(\x0b\x32\x1b.basicmanagement.RoleDataVo\"|\n\nRoleDataVo\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x10\n\x08userName\x18\x02 \x01(\t\x12\x13\n\x0b\x63ustomerNum\x18\x03 \x01(\x05\x12\x11\n\tschoolNum\x18\x04 \x01(\x05\x12\x10\n\x08\x63lassNum\x18\x05 \x01(\x05\x12\x12\n\nstudentNum\x18\x06 \x01(\x05\"W\n\x13RequestRoleUserData\x12\x0e\n\x06pageNo\x18\x01 \x01(\x05\x12\x10\n\x08pageSize\x18\x02 \x01(\x05\x12\x10\n\x08roleName\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t2\xe8\x01\n\x10\x42MManagerService\x12\x61\n\x10listRoleUserData\x12$.basicmanagement.RequestRoleUserData\x1a%.basicmanagement.ResponseRoleUserData\"\x00\x12q\n\x18listOperationManagerData\x12\x1a.basicmanagement.RequestId\x1a\x37.basicmanagement.ResponseSchoolListByOperationManagerId\"\x00\x42N\n3com.szwdcloud.basicmanagement.proto.basicmanagementB\x15\x42MManagerServiceProtoP\x01\x62\x06proto3')
)




_REQUESTID = _descriptor.Descriptor(
  name='RequestId',
  full_name='basicmanagement.RequestId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='basicmanagement.RequestId.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=66,
)


_RESPONSESCHOOLLISTBYOPERATIONMANAGERID = _descriptor.Descriptor(
  name='ResponseSchoolListByOperationManagerId',
  full_name='basicmanagement.ResponseSchoolListByOperationManagerId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='basicmanagement.ResponseSchoolListByOperationManagerId.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='basicmanagement.ResponseSchoolListByOperationManagerId.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='schoolInfo', full_name='basicmanagement.ResponseSchoolListByOperationManagerId.schoolInfo', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=184,
)


_SCHOOLINFO = _descriptor.Descriptor(
  name='SchoolInfo',
  full_name='basicmanagement.SchoolInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='basicmanagement.SchoolInfo.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='basicmanagement.SchoolInfo.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='customerType', full_name='basicmanagement.SchoolInfo.customerType', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='teacherNum', full_name='basicmanagement.SchoolInfo.teacherNum', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='classNum', full_name='basicmanagement.SchoolInfo.classNum', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='studentNum', full_name='basicmanagement.SchoolInfo.studentNum', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='CustomerInfo', full_name='basicmanagement.SchoolInfo.CustomerInfo', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=358,
)


_CUSTOMERINFO = _descriptor.Descriptor(
  name='CustomerInfo',
  full_name='basicmanagement.CustomerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='superiorId', full_name='basicmanagement.CustomerInfo.superiorId', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='superiorName', full_name='basicmanagement.CustomerInfo.superiorName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='customerType', full_name='basicmanagement.CustomerInfo.customerType', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=360,
  serialized_end=438,
)


_RESPONSEROLEUSERDATA = _descriptor.Descriptor(
  name='ResponseRoleUserData',
  full_name='basicmanagement.ResponseRoleUserData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='basicmanagement.ResponseRoleUserData.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='basicmanagement.ResponseRoleUserData.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total', full_name='basicmanagement.ResponseRoleUserData.total', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pages', full_name='basicmanagement.ResponseRoleUserData.pages', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pageNo', full_name='basicmanagement.ResponseRoleUserData.pageNo', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pageSize', full_name='basicmanagement.ResponseRoleUserData.pageSize', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='datas', full_name='basicmanagement.ResponseRoleUserData.datas', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=441,
  serialized_end=598,
)


_ROLEDATAVO = _descriptor.Descriptor(
  name='RoleDataVo',
  full_name='basicmanagement.RoleDataVo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='basicmanagement.RoleDataVo.userId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userName', full_name='basicmanagement.RoleDataVo.userName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='customerNum', full_name='basicmanagement.RoleDataVo.customerNum', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='schoolNum', full_name='basicmanagement.RoleDataVo.schoolNum', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='classNum', full_name='basicmanagement.RoleDataVo.classNum', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='studentNum', full_name='basicmanagement.RoleDataVo.studentNum', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=600,
  serialized_end=724,
)


_REQUESTROLEUSERDATA = _descriptor.Descriptor(
  name='RequestRoleUserData',
  full_name='basicmanagement.RequestRoleUserData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pageNo', full_name='basicmanagement.RequestRoleUserData.pageNo', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pageSize', full_name='basicmanagement.RequestRoleUserData.pageSize', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='roleName', full_name='basicmanagement.RequestRoleUserData.roleName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='basicmanagement.RequestRoleUserData.name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=726,
  serialized_end=813,
)

_RESPONSESCHOOLLISTBYOPERATIONMANAGERID.fields_by_name['schoolInfo'].message_type = _SCHOOLINFO
_SCHOOLINFO.fields_by_name['CustomerInfo'].message_type = _CUSTOMERINFO
_RESPONSEROLEUSERDATA.fields_by_name['datas'].message_type = _ROLEDATAVO
DESCRIPTOR.message_types_by_name['RequestId'] = _REQUESTID
DESCRIPTOR.message_types_by_name['ResponseSchoolListByOperationManagerId'] = _RESPONSESCHOOLLISTBYOPERATIONMANAGERID
DESCRIPTOR.message_types_by_name['SchoolInfo'] = _SCHOOLINFO
DESCRIPTOR.message_types_by_name['CustomerInfo'] = _CUSTOMERINFO
DESCRIPTOR.message_types_by_name['ResponseRoleUserData'] = _RESPONSEROLEUSERDATA
DESCRIPTOR.message_types_by_name['RoleDataVo'] = _ROLEDATAVO
DESCRIPTOR.message_types_by_name['RequestRoleUserData'] = _REQUESTROLEUSERDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestId = _reflection.GeneratedProtocolMessageType('RequestId', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTID,
  __module__ = 'BMManagerService_pb2'
  # @@protoc_insertion_point(class_scope:basicmanagement.RequestId)
  ))
_sym_db.RegisterMessage(RequestId)

ResponseSchoolListByOperationManagerId = _reflection.GeneratedProtocolMessageType('ResponseSchoolListByOperationManagerId', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSESCHOOLLISTBYOPERATIONMANAGERID,
  __module__ = 'BMManagerService_pb2'
  # @@protoc_insertion_point(class_scope:basicmanagement.ResponseSchoolListByOperationManagerId)
  ))
_sym_db.RegisterMessage(ResponseSchoolListByOperationManagerId)

SchoolInfo = _reflection.GeneratedProtocolMessageType('SchoolInfo', (_message.Message,), dict(
  DESCRIPTOR = _SCHOOLINFO,
  __module__ = 'BMManagerService_pb2'
  # @@protoc_insertion_point(class_scope:basicmanagement.SchoolInfo)
  ))
_sym_db.RegisterMessage(SchoolInfo)

CustomerInfo = _reflection.GeneratedProtocolMessageType('CustomerInfo', (_message.Message,), dict(
  DESCRIPTOR = _CUSTOMERINFO,
  __module__ = 'BMManagerService_pb2'
  # @@protoc_insertion_point(class_scope:basicmanagement.CustomerInfo)
  ))
_sym_db.RegisterMessage(CustomerInfo)

ResponseRoleUserData = _reflection.GeneratedProtocolMessageType('ResponseRoleUserData', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEROLEUSERDATA,
  __module__ = 'BMManagerService_pb2'
  # @@protoc_insertion_point(class_scope:basicmanagement.ResponseRoleUserData)
  ))
_sym_db.RegisterMessage(ResponseRoleUserData)

RoleDataVo = _reflection.GeneratedProtocolMessageType('RoleDataVo', (_message.Message,), dict(
  DESCRIPTOR = _ROLEDATAVO,
  __module__ = 'BMManagerService_pb2'
  # @@protoc_insertion_point(class_scope:basicmanagement.RoleDataVo)
  ))
_sym_db.RegisterMessage(RoleDataVo)

RequestRoleUserData = _reflection.GeneratedProtocolMessageType('RequestRoleUserData', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTROLEUSERDATA,
  __module__ = 'BMManagerService_pb2'
  # @@protoc_insertion_point(class_scope:basicmanagement.RequestRoleUserData)
  ))
_sym_db.RegisterMessage(RequestRoleUserData)


DESCRIPTOR._options = None

_BMMANAGERSERVICE = _descriptor.ServiceDescriptor(
  name='BMManagerService',
  full_name='basicmanagement.BMManagerService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=816,
  serialized_end=1048,
  methods=[
  _descriptor.MethodDescriptor(
    name='listRoleUserData',
    full_name='basicmanagement.BMManagerService.listRoleUserData',
    index=0,
    containing_service=None,
    input_type=_REQUESTROLEUSERDATA,
    output_type=_RESPONSEROLEUSERDATA,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='listOperationManagerData',
    full_name='basicmanagement.BMManagerService.listOperationManagerData',
    index=1,
    containing_service=None,
    input_type=_REQUESTID,
    output_type=_RESPONSESCHOOLLISTBYOPERATIONMANAGERID,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BMMANAGERSERVICE)

DESCRIPTOR.services_by_name['BMManagerService'] = _BMMANAGERSERVICE

# @@protoc_insertion_point(module_scope)
