# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import HBQuestionDataExtentionProto_pb2 as HBQuestionDataExtentionProto__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


class HBQuestionDataExtentionServiceStub(object):
  """HbaseQuestionDataExtention表相关的QuestionDataExtention
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.insertData = channel.unary_unary(
        '/hbaseservice.HBQuestionDataExtentionService/insertData',
        request_serializer=HBQuestionDataExtentionProto__pb2.QuestionDataExtention.SerializeToString,
        response_deserializer=HBQuestionDataExtentionProto__pb2.QuestionDataExtentionList.FromString,
        )
    self.queryDataByRowkey = channel.unary_unary(
        '/hbaseservice.HBQuestionDataExtentionService/queryDataByRowkey',
        request_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
        response_deserializer=HBQuestionDataExtentionProto__pb2.QuestionDataExtentionValue.FromString,
        )


class HBQuestionDataExtentionServiceServicer(object):
  """HbaseQuestionDataExtention表相关的QuestionDataExtention
  """

  def insertData(self, request, context):
    """向表中写数据
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def queryDataByRowkey(self, request, context):
    """通过id查询表中的字段
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HBQuestionDataExtentionServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'insertData': grpc.unary_unary_rpc_method_handler(
          servicer.insertData,
          request_deserializer=HBQuestionDataExtentionProto__pb2.QuestionDataExtention.FromString,
          response_serializer=HBQuestionDataExtentionProto__pb2.QuestionDataExtentionList.SerializeToString,
      ),
      'queryDataByRowkey': grpc.unary_unary_rpc_method_handler(
          servicer.queryDataByRowkey,
          request_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
          response_serializer=HBQuestionDataExtentionProto__pb2.QuestionDataExtentionValue.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'hbaseservice.HBQuestionDataExtentionService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
